#!/bin/sh

if [ -e fatlib ]; then rm -r fatlib; fi
fatpack tree $(fatpack packlists-for strictures.pm Module/Runtime.pm Moo.pm JSON/PP.pm MRO/Compat.pm Class/C3.pm Algorithm/C3.pm Class/Method/Modifiers.pm Role/Tiny.pm CPS/Future.pm)
rm lib/Object/Remote/FatNode.pm
(
  echo 'package Object::Remote::FatNode;
our $DATA = do { local $/; <DATA> };
1;
__DATA__
';
  fatpack file;
  cat bin/object-remote-node
)>FatNode.pm.new
mv FatNode.pm.new lib/Object/Remote/FatNode.pm
rm -r fatlib
